version: '3'
services:
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "yourStrong(!)Password"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
    webapi:
        build: .
        ports: 
            - "8001:80"